version: '3.1'

services:
  engine:
    image: qlikcore/engine:12.1070.0
    command: -S AcceptEULA=yes
    ports:
      - 9076:9076
    volumes:
      - ${APPS_PATH:-./data/apps}:/apps

    # Hide output from engine container
    logging:
      driver: "none"

  rendering-tests:
    build: .
    depends_on:
      - engine
    network_mode: host

    # Map artifact folders between host and Docker
    volumes:
      - ./test/rendering/artifacts:/test/rendering/artifacts

